[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.extra_flags = -DCORE_DEBUG_LEVEL=1

; OTA için 2MB app + 2MB app0 + 2MB app1 + 2MB SPIFFS
board_build.partitions = min_spiffs.csv

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    mikalhart/TinyGPSPlus @ ^1.0.2
    greiman/SdFat @ ^2.2.2
    adafruit/RTClib @ ^2.1.1
    coryjfowler/MCP_CAN_lib @ ^1.6.2
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    bblanchon/ESP8266_Async_WebServer_Mock @ ^1.2.0

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=1
    -Wno-format

[env:esp32dev-ota]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
board_upload.flash_size = 16MB

lib_deps =
    ${env:esp32dev.lib_deps}

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=1
    -DENABLE_OTA

[env:esp32dev-test]
platform = espressif32
board = esp32dev
framework = arduino
build_type = debug
lib_deps =
    ${env:esp32dev.lib_deps}
    robtillaart/ACS712 @ ^0.8.1
