[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.extra_flags = -DCORE_DEBUG_LEVEL=1

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    mikalhart/TinyGPSPlus @ ^1.0.2
    greiman/SdFat @ ^2.2.2
    adafruit/RTClib @ ^2.1.1
    coryjfowler/MCP_CAN_lib @ ^1.6.2

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

[env:esp32dev-test]
platform = espressif32
board = esp32dev
framework = arduino
build_type = debug
lib_deps =
    ${env:esp32dev.lib_deps}
    robtillaart/ACS712 @ ^0.8.1
